title: Bendemeer Secondary School
url: https://bendemeersec.moe.edu.sg
favicon: /images/favi-schlogo.png
colors:
  primary-color: "#0f469e"
  secondary-color: "#f8bf1c"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: In Bendemeer Secondary, we believe that every student can shine and
  achieve his or her potential, anchored on our strong mission to build
  character, nurture learners and serve the community. The collective efforts of
  our teachers and students have borne fruits of labour which have made us
  distinctive and sustained the Bendemeer Heartbeat.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moe-bendemeersec-staging.netlify.app
prod: https://moe-bendemeersec-prod.netlify.app
shareicon: /images/hero-banner02.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: try-resource-room
